### ISSUE TITLE
Test results with same timestamp/patient/REDCap form name always overwrite those occuring earlier in file

### ISSUE THREAD

**Issue by nrejack** [ctsit/redi#119]
Test results that have the same patient, same timestamp, and same REDCap form name will always import the result that comes latest in the file due to RED-I overwriting the results that come earlier in the file. Consider the following two rows:

### THIS IS FAKE DATA ###
"HCV RNA, PCR, QUANT","11011-4","123456789",,,"IU/mL","1903-01-02 12:00:00","1903-01-02 12:00:00","999-1234"
"HCV RNA, PCR, QUANT","11011-4","8.09",,,"Log IU/mL","1903-01-02 12:00:00","1903-01-02 12:00:00","999-1234"

Because they occur for the same patient, on the same timestamp, for the same test (coded 11011-4), the second row will be imported. 

This causes a problem when the second row is rejected due to invalid units. As a result, no value is imported for the date.
The suggested solution is to add preprocessing rules that remove invalid units at the onset. This would allow the valid, correct data for that date and patient to flow through.

**Comment by indera** [comment]
This was fixed by Ruchi in https://github.com/ctsit/redi/commit/cb97f24b2809c6d1e4c849d22174aab2b514f913

**Comment by nrejack** [comment]
released in version 0.14.0 7e25a045310292a0cfb28419707cb39e35526724
