### ISSUE TITLE
Code without per-file licensing is hard to attribute when copying it to other projects

### ISSUE THREAD

**Issue by pbchase** [ctsit/redi#130]
When I borrowed some code from RED-I it was hard to manage the licensing and contributors data for the pieces I took.  It would be simpler to borrow code from RED-I if code files had per-file licensing.  

I added such content to the files I took from RED-I and thought those might be a good addition to the RED-I.  You can see this in https://github.com/susom/redcap-extras/pull/3, specifically in these files: 

* https://github.com/pbchase/redcap-extras/blob/master/vagrant/aliases
* https://github.com/pbchase/redcap-extras/blob/master/vagrant/bootstrap.sh
* https://github.com/pbchase/redcap-extras/blob/master/vagrant/bootstrap_functions.sh

Philip

**Comment by nrejack** [comment]
released in v0.14.0 7e25a045310292a0cfb28419707cb39e35526724
