### ISSUE TITLE
Site name in Night Run Report email's subject line...

### ISSUE THREAD

**Issue by UF-Buck-GitHub** [ctsit/redi#133]
I would like to have the actual site that the report is generated for to be in the actual subject line of the email that is forwarded. i.e. "Data Import Report" becomes ---> "[site name ] Data Import Report"

Site names being: SLU, UPENN, NEB, UF, UNC, etc....

**Comment by nrejack** [comment]
released in version 0.14.0 7e25a045310292a0cfb28419707cb39e35526724
