### ISSUE TITLE
Add option to run against local CSV file

### ISSUE THREAD

**Issue by nrejack** [ctsit/redi#134]
RED-I has two options for a data source: 
1. fetch a CSV file from an SFTP server specified in the settings.ini file, using the '-e' flag
2. run with a local XML file specified in the settings.ini file.

When using option 1, the CSV file is converted to an XML file before processing. There is no way to feed a local CSV file into option 2 however, without using a separate XML conversion utility. This makes performing test runs on modified data files more time-consuming than it should be. 

RED-I should be modified to allow local CSV files as input, in addition to XML.

This is related to issue #135 .

**Comment by indera** [comment]
That would allow to re-use some code too :)

**Comment by ufl-taeber** [comment]
If you want to upload a file directly, use "direct mode":

https://github.com/ufl-taeber/redi/commit/c71014629bf03dd434e356e159f48cca3ff3743e

**Comment by nrejack** [comment]
This has been implemented in fb61162ad6771a1268113e6f6afeb2eb98ee48d3
