### ISSUE TITLE
Make RED-I's data fetch more modular

### ISSUE THREAD

**Issue by nrejack** [ctsit/redi#135]
RED-I lacks the ability to pre-process data, after the fetch phase but before the data processing phase. Removing bad data which could cause RED-I errors, or correcting errors in the source data, such as incorrect units and out-of-bounds data values, is not a flexible or modular process.

Add the ability to insert data preprocessors after fetching data from an SFTP server or after running on a local CSV or XML file. These would be small, self-contained data processors that perform one function on the data and then pass it on to the next phase, and could be inserted in any order. This is related to issue #134 .

**Comment by indera** [comment]
Great idea -- this is related to #134

**Comment by nrejack** [comment]
Released in 0.14.1 with commit: caa5c46f033b07bbc460a4f7d228df7ace6d0846. New preprocessors can now be added. Data processing after fetching file (XML conversion and XML character entity substitution) has also been relocated from GetEmrData.
