### ISSUE TITLE
Spin off redcap_records.py

### ISSUE THREAD

**Issue by pbchase** [ctsit/redi#165]
Should we spin off redcap_records.py into its own project?  Or perhaps into a project with other REDCap command line tools?  I have another REDCap CLI tool called redcap_metadata.py that I never shared.  It's a fork of redcap records that exports REDCap metadata.  

redcap_records is kind of a second class citizen in RED-I, but I need it to be treated as a first class citizen.  I wrote it and still like to use it on occasion to test API functionality.  For me it is the easiest way to see real-world REDCap API behavior.  I need it and it's brethren to be in my path so I can invoke them any time and any place.  

Any objections?  I can make the new projects and be their caretaker.  I'd like to do that.

Philip

**Comment by indera** [comment]
No objections, as long as we keep the contributors list ;) and replace/fix the existing occurrences of "redcap_records" we should be good :+1: 

https://github.com/ctsit/redi/search?utf8=%E2%9C%93&q=redcap_records

**Comment by ufl-taeber** [comment]
:+1:

**Comment by pbchase** [comment]
Glad you like it.  I already did some of the work.  I'll get the repo published and package sent to pypi, then issue a pull request for the removal from RED-I.

**Comment by pbchase** [comment]
I made all the changes Andrei suggested in pull request #166. I also added the redcap_cli package to the packages required for installation of redi. 

I also updated the file ./requirements.txt.  I have to wonder if that last file is junk, but I updated it none-the-less.

**Comment by nrejack** [comment]
Pull request #166 closed.
